# Generated by Django 5.1.4 on 2025-02-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='duty_role',
            new_name='duty_role_id',
        ),
    ]
