# Generated by Django 5.1.4 on 2025-01-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
    # migrations.CreateModel(
    #     name='Config',
    #     fields=[
    #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #         ('duty_role', models.CharField(max_length=100)),
    #         ('time_slot', models.TimeField()),
    #     ],
    # ),
    migrations.AddField(
        model_name='roster',
        name='week_start_date',
        field=models.DateField(default=date.today),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='roster',
        name='work_date',
        field=models.DateField(default=date.today),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='roster',
        name='duty_role',
        field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster.config'),
    ),
]