# Generated by Django 5.1.4 on 2025-02-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #    model_name='roster',
        #    name='duty_role',
        #),
        migrations.AddField(
            model_name='roster',
            name='duty_role_id',
            field=models.CharField(db_column='duty_role_id', default='test', max_length=50),
            preserve_default=False,
        ),
    ]
