# Generated by Django 5.1.4 on 2025-02-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_remove_roster_no_of_work_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='no_of_work_hr',
            field=models.FloatField(default=0.0),
        ),
    ]
