# Generated by Django 5.1.4 on 2025-02-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_remove_roster_duty_role_roster_duty_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='duty_role',
        ),
    ]
