# Generated by Django 5.1.4 on 2025-01-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_config_roster_week_start_date_roster_work_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_role', models.CharField(max_length=100)),
                ('time_slot', models.TimeField()),
            ],
        ),
    ]
