# Generated by Django 5.1.4 on 2025-01-24 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_config_roster_week_start_date_roster_work_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='week_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='roster',
            name='work_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
