# Generated by Django 5.1.4 on 2025-02-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_roster_no_of_work_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('onsell', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('shelved_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BakeryProductRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('restock_quantity', models.PositiveIntegerField()),
                ('delivery_date', models.DateField()),
                ('order_by', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
