# Generated by Django 5.1.4 on 2025-01-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_rosterconfig_duty_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='no_of_work_hr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='roster',
            name='duty_role',
            field=models.CharField(default='old', max_length=50),
            preserve_default=False,
        ),
    ]
