# Generated by Django 5.1.4 on 2025-02-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_bakeryproduct_bakeryproductrestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryproduct',
            name='item_name_CHI',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
