# Generated by Django 5.1.4 on 2025-01-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_roster_no_of_work_hr_alter_roster_duty_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='staff',
        ),
        migrations.AddField(
            model_name='roster',
            name='staff_name',
            field=models.CharField(default='old', max_length=100),
            preserve_default=False,
        ),
    ]
