# Generated by Django 5.1.4 on 2025-03-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_bakeryproduct_item_name_chi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryproduct',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
