# Generated by Django 5.1.4 on 2025-01-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_remove_roster_staff_roster_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='week_start_date',
            field=models.DateField(),
        ),
    ]
