# Generated by Django 5.1.4 on 2025-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_bakeryproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryproduct',
            name='image_url_cat',
            field=models.URLField(blank=True),
        ),
    ]
