# Generated by Django 5.1.4 on 2025-01-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_alter_roster_week_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='work_date',
            field=models.DateField(),
        ),
    ]
