# Generated by Django 5.1.4 on 2025-02-01 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_alter_roster_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='duty_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.rosterconfig'),
        ),
    ]
