# Generated by Django 5.1.4 on 2025-03-29 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_bakeryproduct_image_url_cat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('business_time', models.TimeField()),
                ('amex', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debit_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mastercard', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unionpay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wonderful_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gift_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('redeem_points', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
