# Generated by Django 5.1.4 on 2025-03-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_remove_dailyrevenue_user_dailyrevenue_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrevenue',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
