# Generated by Django 5.1.4 on 2025-04-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
